import 'package:flutter/material.dart';

const kMainColor = Color(0xFFFFC12F);
const kSecondaryColor = Color(0xFFFFE6AC);
const kUnSelectColor = Color(0xFFC1BDB8);
const kProductLocation = 'productLocation';
const kProductDescription = 'productDescription';
const kProductCategory = 'productCategory';
const kProductPrice = 'productPrice';
const kProductName = 'productName';
const kProducts = 'products';
const kMan = 'men';
const kWomen = 'women';
const kBaby = 'Baby';
const kShoes = 'shoes';
const kOrders = 'orders';
const kOrdersDetails = 'ordersDetails';
const kTotalPrice = 'totalPrice';
const kAddress = 'address';
const kCount= 'count';
